FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

CMD [ "npm", "start" ]

FROM node:18-alpine

WORKDIR /app

COPY --from=builder ./node_modules ./node_modules
COPY . .

EXPOSE 3000  

ENV NODE_ENV=production 

CMD [ "npm", "start" ]